<a href="https://colab.research.google.com/github/nurniahamid/Analisis_Sentimen-/blob/main/Scraping_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.11/dist-packages (1.2.7)

In [ ]:
from google_play_scraper import app, reviews, Sort, reviews_all
import pandas as pd

In [ ]:
from google_play_scraper import reviews, Sort

scrape_review, _ = reviews(
    'com.lemon.lvoverseas',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=11000
)

In [ ]:
import csv

with open('review_capcut.csv', mode='w', newline='', encoding='utf-8') as file :
  writer = csv.writer(file)
  writer.writerow(['Review'])
  for review in scrape_review :
    writer.writerow([review['content']])

In [ ]:
reviews_capcut_df = pd.DataFrame(scrape_review)
reviews_capcut_df.shape
reviews_capcut_df.head()
reviews_capcut_df.to_csv('review_capcut.csv', index=False)

reviews_capcut_df = pd.DataFrame(scrape_review)

jumlah_review, jumlah_kolom = reviews_capcut_df.shape
print(f"Jumlah review: {jumlah_review}")
print(f"Jumlah kolom: {jumlah_kolom}")

reviews_capcut_df.head()

Jumlah review: 11000
Jumlah kolom: 11

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,b37b3a5a-b1d7-45d3-b408-93b529a47b0b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,amandanpenting,5,0,None,2025-04-27 08:38:36,None,NaT,None
1,728b62fd-1d4b-4d72-8431-0f84ae15a54f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,😻😭💜💛👟🏠🐱👟😊👟🐱👟🐱🐭👟😊😊🐩😁👟😁🐩,5,0,14.1.0,2025-04-27 07:25:37,None,NaT,14.1.0
2,d90645c6-a681-431f-aef1-d7c7a88da4d5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Capcut capucino centut,2,0,None,2025-04-27 07:10:48,None,NaT,None
3,3fe30fd2-597a-4272-bcdc-8c32c2eb74ff,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,aplikasi ini sangat cocok untuk mengedit,5,1,None,2025-04-27 01:52:50,None,NaT,None
4,1f79ded1-9241-432c-81d1-ca52141c2ce5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Jujurly ini apk nya bagus cuman apk nya tuh ba...,5,0,None,2025-04-26 13:39:27,None,NaT,None

In [ ]:
reviews_capcut_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              11000 non-null  object
 1   userName              11000 non-null  object
 2   userImage             11000 non-null  object
 3   content               11000 non-null  object
 4   score                 11000 non-null  int64
 5   thumbsUpCount         11000 non-null  int64
 6   reviewCreatedVersion  5769 non-null   object
 7   at                    11000 non-null  datetime64[ns]
 8   replyContent          36 non-null     object
 9   repliedAt             36 non-null     datetime64[ns]
 10  appVersion            5769 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 945.4+ KB

In [ ]:
reviews_capcut_df = reviews_capcut_df[['userName','content', 'score', 'at']]

In [ ]:
reviews_capcut_df.head()

,userName,content,score,at
0,Pengguna Google,amandanpenting,5,2025-04-27 08:38:36
1,Pengguna Google,😻😭💜💛👟🏠🐱👟😊👟🐱👟🐱🐭👟😊😊🐩😁👟😁🐩,5,2025-04-27 07:25:37
2,Pengguna Google,Capcut capucino centut,2,2025-04-27 07:10:48
3,Pengguna Google,aplikasi ini sangat cocok untuk mengedit,5,2025-04-27 01:52:50
4,Pengguna Google,Jujurly ini apk nya bagus cuman apk nya tuh ba...,5,2025-04-26 13:39:27

In [ ]:
clean_reviews = reviews_capcut_df.dropna()
clean_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   userName  11000 non-null  object
 1   content   11000 non-null  object
 2   score     11000 non-null  int64
 3   at        11000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 343.9+ KB